language: node_js
node_js:
- '0.10'
- '0.11'
- '0.12'
- '4.0'
- '5.0'
- iojs
sudo: false
after_script: npm install codecov.io && cat ./coverage/lcov.info | codecov
deploy:
  - provider: npm
    email: tituswormer@gmail.com
    api_key:
        secure: aa4+EwFZM4Jrkf9hD8EMa4QyEoOtshX0zhaoWr1ootJMJ9adGHt1IdoOWKWy/vIYg+vITApMb5/Ilb4Eb5OUphI83LTFfwaoNpcPkj7Y/xrpNSF9Ktep+yk1l3TGrcs+Y3QRsG5s25bz0+UY5Rxr8x31qu57uAxiZQWsYQTF+beZfY8Tkx4+F0F9ti/8xxSfe6bgxQqWWn8nZrO2QD635LYIDMY0OTbnhoSqdTdpuLvy7bRpBDoTJokUr37/NOkQgG8fhpJBI9uQIKTarogGqxYMTXpCxuRVA8sLVA7mOYbPdEXuofuhhhhzEvkYuCmqk5Dy3IBTjYRHKhuXiG0oa4xpOjGEjXsC1wN2R3JY+KMyHzCtVPEhVarBtJLTBjd2YB6Qw9bQOIJzRl8Pf0Edrijt2xNKKQqvYWSqabORjETWbYvhc5MNP8epeeJlVBMlhmyQ6Eopqa/j2cccZWvipTjZY3PzmlyC9H5w4tlnywY7E6fPQcFDEW7dr5oCJT2yjb1vd7hcZirc30CtIXbN08KASIDvH3TJg6w/dvnwe3x1jqmCZHsGf0UjJ4dxNHB/Vip7icUbB1JkX4Vx18+tR6uB6CC7mQD7ItAUfgtVdP+7I+3REw5Pa/x+MrfTSqXKZm2ccHQNNCxek0l/RDrylPYv4+YmckJ8KjdFwUFsqYE=
    on:
      tags: true
  - provider: releases
    api_key:
        secure: y93/UnR+XSXYGiXksm1hTvC7Q5/1TK55HiCb9wIRiQ3ogbRPdPGo58Arsk+mJvg5jj8LkbISMiiz9o/kuO8RexYQkzxQAHoHgCxcd+COa3QCwkD3piIpTvvE6NNcuWCKwNcikubnEntnGpFXSKpTkJrw5Dwp6M0+SkaZs1nJc+yb8oVm39JRs5dkVtc7QzTU+/uf8gUkGNIADd7heljuXqpUf+Jz4ocikPolhZ3lboXf6iz0gxEVVEkJDYfiO+J7zbvrvGjWxzGJ+XGzGQo6rjXgxcVBAjB8mgBvnZZkoW9+K0Jn039VEXWW2jYC7792aop1DxtJaESz9wwu98e/t7GWf8F6FzZ0jTGJ9Lhh1baRuoa5S1VrGlHn8xbjpKPBcQfaXXaTr0hYIZXs3CAl4uMwbdar1UpmUnCYKwafw/Ewf9cRb7im/VBlDE+47X2wNBSd1JidO6LYf1rVhglHN6I5GfuL7pWVoGKy6HU8LVukLI0GRnVl1QxEhKQefFIbkrh3jEUlL7oz3kn+Oj69y2jXDQtJP4Jr4xynBW5AMo0rk8NW4fKZKb+ks4Ee879Th/993AfQ4BkWnHI0oMCVaiVhiwkzU9zHSAU05Y32WbkNos/uPDScUmsJQXP3rl7R7NaSUJ0btQHwzV066wK8RMUm/ViFRafM4AB+QskdL4U=
    file:
      - "unified-bridge.js"
      - "unified-bridge.min.js"
    on:
      tags: true
